import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {rm} from 'node:fs/promises';
import {join} from 'node:path';
const testHome=await mkdtemp(join(tmpdir(),'travai-receipts-'));
process.env.HOME=testHome;
const {createTask}=await import('../local-bridge/task-orchestrator-v970.mjs');
const {runNextApprovedTaskStep}=await import('../local-bridge/task-runner-v971.mjs');
const {readAgentReceipts}=await import('../local-bridge/agent-receipts-v1318.mjs');

const task=createTask({steps:[{action:'open-app',input:{app:'Safari'}}]});
const result=await runNextApprovedTaskStep(task.id,{approved:true,run:async()=>({stdout:'',stderr:''})});
assert.equal(result.task.status,'completed');
const receipts=await readAgentReceipts();
const found=receipts.find(x=>x.taskId===task.id);
assert.ok(found);
assert.equal(found.action,'open-app');
assert.equal(found.result,'executed');
assert.equal('input' in found,false);
assert.equal('output' in found,false);
const failedTask=createTask({steps:[{action:'set-volume',input:{volume:50}}]});
const failed=await runNextApprovedTaskStep(failedTask.id,{approved:true,run:async()=>{throw new Error('simulated-executor-failure')}});
assert.equal(failed.done,false);
assert.equal(failed.task.status,'retry-pending');
assert.ok((await readAgentReceipts()).some(x=>x.taskId===failedTask.id&&x.result==='failed'));

const unapprovedTask=createTask({steps:[{action:'toggle-mute',input:{muted:true}}]});
const unapproved=await runNextApprovedTaskStep(unapprovedTask.id,{approved:false,run:async()=>{throw new Error('executor-should-not-run')}});
assert.equal(unapproved.error,'LOCAL_APPROVAL_REQUIRED');
assert.equal(unapproved.task.status,'retry-pending');
assert.ok((await readAgentReceipts()).some(x=>x.taskId===unapprovedTask.id&&x.result==='failed'));
await rm(testHome,{recursive:true,force:true});
console.log('v13.18 execution receipts integration: PASS');
