import assert from 'node:assert/strict';
import {durableCreateRequest} from '../local-bridge/pairing-state-v1390.mjs';
import {pairingDiagnostics} from '../local-bridge/pairing-diagnostics-v1330.mjs';
await durableCreateRequest({requestId:'c'.repeat(32),label:'diagnostic test'});
const d=await pairingDiagnostics();
assert.equal(d.ok,true);
assert.equal(d.counts.pending>=1,true);
assert.equal(d.policy.durableCrossProcessState,true);
assert.equal(d.policy.exposesSessionTokens,false);
assert.equal(d.policy.exposesClaimSecrets,false);
assert.equal(d.policy.exposesApprovalHashes,false);
assert.equal(d.policy.browserApproval,false);
assert.equal(JSON.stringify(d).includes('sessionToken'),false);
assert.equal(JSON.stringify(d).includes('claimSecret'),false);
console.log('v13.10 pairing diagnostics: PASS');
