import assert from 'node:assert/strict';
import {loadReleaseIdentity,identityMatches,identityPolicy,decodeTravAIVersion} from '../local-bridge/runtime-identity-v1160.mjs';
const id=await loadReleaseIdentity();
assert.equal(id.service,'travai-local-runtime');
assert.equal(id.release,decodeTravAIVersion(id.packageVersion));
assert.equal(decodeTravAIVersion('13900000000.0.0'),'13.9.0');
assert.equal(decodeTravAIVersion('131000000000.0.0'),'13.10.0');
assert.equal(decodeTravAIVersion('131100000000.0.0'),'13.11.0');
assert.equal(id.protocol,'travai-local/v1');
assert.equal(identityMatches(id,{...id}),true);
assert.equal(identityMatches({...id,packageVersion:'old'},id),false);
assert.equal(identityPolicy.secretFree,true);
assert.equal(identityPolicy.includesSessionToken,false);
assert.equal(identityPolicy.includesApprovalAuthority,false);
assert.equal(identityPolicy.releaseDerivedFromPackage,true);
console.log('runtime identity binding: PASS');
