import assert from 'node:assert/strict';
import {listFavorites,setFavorite,favoritePolicy} from '../local-bridge/task-favorites-v991.mjs';
assert.equal(listFavorites().includes('health-check'),true);
assert.equal(setFavorite('mute-mac',true).ok,true);
assert.equal(listFavorites().includes('mute-mac'),true);
assert.equal(setFavorite('workspace-ready',true).ok,true);
assert.equal(setFavorite('work-wrap',true).ok,true);
assert.equal(setFavorite('unknown',true).ok,false);
assert.equal(favoritePolicy.dynamicTemplateCatalog,true);
assert.equal(favoritePolicy.arbitraryActions,false);
console.log('v10.8.0 favorites catalog sync: PASS');
